[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[invariant]
fail_on_revert = false

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
op_sepolia = "${OP_SEPOLIA_RPC_URL}"
testnet = "${TESTNET_RPC_URL}"
rmm_testnet = "${RMM_TESTNET_RPC_URL}"

unknown_chain = { key = "LuGoYcb33BtmXfP5WOswj5nBVx2dY5H1", chain = 1, url = "https://virtual.mainnet.rpc.tenderly.co/8f2d26b8-0108-48c0-8eba-2d40ae7954c8" }
