[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 1
optimizer = true

[invariant]
fail_on_revert = false

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
op_sepolia = "${OP_SEPOLIA_RPC_URL}"
testnet = "${TESTNET_RPC_URL}"

unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 8888, url = "${TESTNET_RPC_URL}" }
