[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[invariant]
fail_on_revert = false

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
op_sepolia = "${OP_SEPOLIA_RPC_URL}"
testnet = "${TESTNET_RPC_URL}"
