[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer_runs = 1
optimizer = true

[invariant]
fail_on_revert = false

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
op_sepolia = "${OP_SEPOLIA_RPC_URL}"
testnet = "${TESTNET_RPC_URL}"

unknown_chain = { key = "", chain = 753712, url = "https://virtual.mainnet.rpc.tenderly.co/ab7a4b34-a4da-4803-8130-01cf2230dbe6" }
